config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get "/home", to: "pages#home", as: "home"
  get "/about", to: "pages#about", as: "about"
  get "bookings/confirmation", to: "bookings#confirmation", as: "confirmation"
  patch "bookings/confirmation", to: "bookings#update", as: "update_bookings"


  

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
  get "/bookings/new/search", to: "bookings#search", as: "search"
  
  resources :bookings, only: [:new, :index, :show, :create, :destroy]

  # shallow: true is redundant for demons
  resources :demons, shallow: true, only: [:new, :index, :show, :create, :destroy] do
    resources :reviews, shallow: true, only: [:create, :destroy]
  end

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :demon
end

app/models/demon.rb
class Demon < ApplicationRecord
  scope :not_booked, ->(booked_demons) { where.not(id: booked_demons) }
  scope :search_by_name, ->(name, not_booked_demons) { not_booked_demons.where("lower(name) LIKE ?", "%#{name.strip.downcase}%") }

  belongs_to :user

  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :demon
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  # Always use the symbol: value notation
  belongs_to :resource,
             polymorphic: true,
             optional: true

  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings, dependent: :destroy
  has_many :demons, dependent: :destroy
  has_many :reviews

  after_create :assign_default_role

  validate :must_have_a_role, on: :update

  def my_demon_bookings
    Booking.where(demon_id: self.demons)
  end

  private

  def must_have_a_role
    unless roles.any?
      errors.add(:roles, "Must have at least one role")
    end
  end

  def assign_default_role
    self.add_role(:newuser) if self.roles.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_user_params, if: :devise_controller?

  include Pundit::Authorization

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_back(fallback_location: root_path)
  end

  def configure_permitted_user_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :get_user, only: [:index, :new, :create, :confirmation, :update]
  before_action :get_not_booked_demons, only: [:new, :search]
  before_action :get_datetime, only: [:create]

  def index
    # includes saves you from N + 1 queries. Now the DB will only get queried once to get all demons
    # associated with the bookings
    @bookings = @user.bookings.includes(:demon)
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new()
    # The controller shouldn't decide what components get rendered in the view
    @search = true
  end

  # You could consider incorporating the search as part of the DemonsController#index
  def search
    @demons = Demon.search_by_name(params[:name], @demons) if params[:name].present?

    @booking = Booking.new
    @search = true
    render :new
  end

  def create
    # This should just be strong params
    @booking = Booking.new(booking_params)
    @booking.user = current_user

    if @booking.save
      redirect_to bookings_path, notice: 'Booking was successfully created.'
    else
      redirect_to new_booking_path, alert: 'Booking was not created.'
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path, status: :see_other
  end

  def confirmation
    @bookings = @user.my_demon_bookings
  end

  def update
    @booking = Booking.find(params[:booking_id])
    @booking.toggle! :approved
    @booking.save
    UserMailer.with(user: @booking.user).confirmation_email.deliver_now
  end

  private

  def booking_params
    # Missing the permitted attributes
    params.require(:booking).permit(:from_date, :to_date, :demon_id)
  end

  def get_not_booked_demons
    # This belongs in the booking model
    @bookings = Booking.all
    booked_demons = @bookings.map { |booking| booking.demon }
    @demons = Demon.not_booked(booked_demons)
  end

  def get_user
    @user = current_user
  end

  def get_datetime
    # Unnecessary
    @from_date = DateTime.new(booking_params["from_date(1i)"].to_i,
                 booking_params["from_date(2i)"].to_i,
                 booking_params["from_date(3i)"].to_i,
                 booking_params["from_date(4i)"].to_i,
                 booking_params["from_date(5i)"].to_i)

    @to_date = DateTime.new(booking_params["to_date(1i)"].to_i,
                           booking_params["to_date(2i)"].to_i,
                           booking_params["to_date(3i)"].to_i,
                           booking_params["to_date(4i)"].to_i,
                           booking_params["to_date(5i)"].to_i)          
  end
end

app/controllers/demons_controller.rb
class DemonsController < ApplicationController
  before_action :get_demons, only: [:index, :new]
  before_action :get_user, only: [:show, :create]

  def index
    # Talk about pagination
  end

  def show
    @demon = Demon.find(params[:id])
    @review = Review.new
  end

  def new
    @demon = Demon.new
  end

  def create
    @demon = Demon.new({**demon_params, user_id: @user.id})

    if @demon.save
      redirect_to demons_path, notice: 'Demon was successfully created.'
    else
      redirect_to new_demon_path, alert: 'Demon was not created.'
    end
  end

  private

  def demon_params
    params.require(:demon).permit(:name, :speciality, :location, :picture_url)
  end

  def get_user
    @user = current_user
  end

  def get_demons
    @demons = Demon.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :about]

  def home
  end

  def about
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to demon_path(@review.demon), status: :see_other
  end

  def create
    @user = current_user
    @demon = Demon.find(params[:demon_id])
    # now you're just flexing, ** is unnecessary
    @review = Review.new(**review_params)
    @review.user = @user
    @review.demon = @demon

    if @review.save
      redirect_to demon_path(@demon), notice: 'Demon was successfully created.'
    else
      redirect_to demon_path(@demon), alert: 'Demon was not created.'
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    authorize @users
  end

  def edit
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update(user_params)
      redirect_to users_path, notice: 'Demon was successfully created.'
    else
      redirect_to edit_user_path(@user), alert: @user.errors[:roles][0]
    end
  end

  private

  def user_params
    params.require(:user).permit(role_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/demons_helper.rb
module DemonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/_booking.html.erb
<%= form_with model: booking, class: "card d-flex flex-column p-3" do |f| %>
  <div class="text-center mb-3">
    <%= image_tag demon.picture_url, style: "max-width: 15rem" %>
  </div>
  <div class="d-flex flex-column align-items-center mb-3">
    <%= f.hidden_field :demon_id, value: demon.id %>
    <h4><%= f.label demon.name, class: "mb-3" %></h4>
    <ul class="list-group">
      <li class="list-group-item d-flex justify-content-center bg-info">
        <span class="me-3">Location:</span>
        <span> <%= demon.location %></span>
      </li>
      <li class="list-group-item d-flex justify-content-between">
        <%= f.label :from_date, class: "me-3" %>
        <div class="">
          <%= f.datetime_select :from_date, :minute_step => 15 %>
        </div>
      </li>
      <li class="list-group-item d-flex justify-content-between">
        <%= f.label :to_date %>
        <div class="">
          <%= f.datetime_select :to_date, :minute_step => 15 %>
        </div>
      </li>
    </ul>
  </div>
  <%= f.submit class: "btn btn-success align-self-center" %>
<% end %>

app/views/bookings/_form.html.erb
<%= form_with url: update_bookings_path, method: :patch do |f| %>
<%= f.check_box booking.approved, checked: booking.approved,  onchange: "this.form.submit();"%>
<%= f.hidden_field :booking_id, value: booking.id %>
<% end %>

app/views/bookings/confirmation.html.erb
<h3>Please confirm this booking </h3>

<div>
  <% @bookings.each do |booking| %>
    <div>
      <%= link_to booking.demon.name, booking %>
      <%=  render "form", booking: booking %>
    </div>
  <% end %>
</div>

app/views/bookings/index.html.erb
<h2 class="mb-5 text-center">Bookings for <%= @user.name %></h2>
<div class="d-flex justify-content-center">
  <ul class="list-group">
    <% @bookings.each do |booking| %>
        <%= link_to booking, class: "list-group-item d-flex justify-content-between align-items-center gap-5" do %>
          <div class="">
            <!-- N+1 Red Alert - Abandon Ship -->
            <h5><%= booking.demon.name %></h5>
            <p class="m-0"><%= booking.demon.location %></p>
          </div>
          <%= button_to "Show this booking", booking, method: :get, class: "btn btn-secondary"%>
        <% end %>
    <% end %>
  </ul>
</div>

app/views/bookings/new.html.erb
<%= content_for(:navbar_search) do %>
  <%= render "shared/navbar_search" %>
<% end %>

<h2 class="text-center mb-5">New booking</h2>
<div class="row row-cols-1 row-cols-md-2 g-4">
  <% @demons.each do |demon| %>
    <div class="col">
      <%= render "booking", demon: demon, booking: @booking, user: @user %>
    </div>
  <% end %>
</div>

app/views/bookings/show.html.erb
<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="<%= @booking.demon.picture_url %>" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title"><%= @booking.demon.name %></h5>
    <p class="card-text">Speciality of your Demon: <%= @booking.demon.speciality %></p>
    <p class="card-text">Location of your Demon: <%= @booking.demon.location %></p>
    <p class="card-text">Your torture starts on: <%= @booking.from_date %></p>
    <p class="card-text">Your torture ends on: <%= @booking.to_date %></p>

    <%= button_to "Delete booking", booking_path, method: :delete, class: "btn btn-danger" %>
  </div>
</div>

app/views/demons/_new_demon.html.erb
<%= form_with model: demon, class: "d-flex flex-column align-items-start gap-2" do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "mb-3 p-2", style: "min-width:300px;" %>
  <%= f.label :speciality %>
  <%= f.text_field :speciality, class: "mb-3 p-2", style: "min-width:300px;" %>
  <%= f.label :location %>
  <%= f.text_field :location, class: "mb-3 p-2", style: "min-width:300px;" %>
  <%= f.label :picture_url %>
  <%= f.text_field :picture_url, class: "mb-5 p-2", style: "min-width:300px;" %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/demons/index.html.erb
<h2 class="mb-5 text-center">Demons</h2>
<div class="text-center d-flex justify-content-center">
    <ul class="list-group">
        <% @demons.each do |demon| %>
            <%= link_to demon, class: "list-group-item d-flex justify-content-between align-items-center gap-3" do %>
                <%= image_tag demon.picture_url, class: "img-fluid", style: "max-width: 100px" %>
                <div>
                    <h5 class="m-0"><%= demon.name %></h5>
                    <p class="m-0"><%= demon.location %></p>
                </div>
                <%= button_to "Show this demon", demon, method: :get, class: "btn btn-secondary"%>
            <% end %>
        <% end %>
        </ul>
</div>

app/views/demons/new.html.erb
<h2 class="mb-5">New demon</h2>
<!-- nice passing the demon explicitly -->
<%= render "new_demon", demon: @demon %>

app/views/demons/show.html.erb
<div class="row">
    <div class="col-md-8">
        <h2 class="mb-5">Demon info</h2>
        <div class="card overflow-hidden" style="max-width: 50rem;">
            <div class="p-3 bg-secondary text-white">
                <h3 class="card-title text-center"><%= @demon.name %></h3>
            </div>
            <%= image_tag @demon.picture_url, class: "card-img-top p-5" %>
            <ul class="list-group list-group-flush">
                <li class="list-group-item text-center"><strong>Speciality:</strong> <%= @demon.speciality %></li>
                <li class="list-group-item text-center"><strong>Location:</strong> <%= @demon.location %></li>
            </ul>
        </div>
    </div>

    <div class="col-md-4">
        <h2 class="mb-5">Reviews:</h2>
        <ul class="list-group mb-3">
            <% @demon.reviews.each do |review| %>
                <%= render "reviews/review", review: review, user: @user %>
            <% end %>
        </ul>
        <%= render "reviews/new_review", demon: @demon, review: @review %>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="bg-primary mt-auto">
  <div class="container">
    <div class="d-flex justify-content-between align-items-center">
      <div class="p-2 me-auto ">
        <h1><%= link_to "IIIKarnov Academy", root_path, class: "navbar-brand m-0 fs-4" %></h1>
      </div>
      <p class="m-0">Additional information</p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="bg-primary">
  <nav class="navbar navbar-expand-lg">
    <div class="container">
      <div class="p-2">
        <h1><%= link_to "IIIKarnov Academy", root_path, class: "navbar-brand m-0 fs-4" %></h1>
      </div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item me-3">
            <% if @search %>
              <%= form_with url: search_path, method: :get, class: "d-flex align-items-center gap-2"  do |f| %>
                <%= f.text_field :name %>
                <%= f.submit "Search", class: "btn" %>
              <% end %>
            <% end %>
          </li>
          <li class="nav-item"><%= link_to "Home", home_path, class: "nav-link #{"active" if current_page?(home_path) || current_page?(root_path)}" %></li>
          <li class="nav-item"><%= link_to "My bookings", bookings_path, class: "nav-link #{"active" if current_page?(bookings_path)}" %></li>
          <li class="nav-item"><%= link_to "New booking", new_booking_path, class: "nav-link #{"active" if current_page?(new_booking_path)}" %></li>
          <li class="nav-item"><%= link_to "Demons", demons_path, class: "nav-link #{"active" if current_page?(demons_path)}" %></li>
          <li class="nav-item"><%= link_to "New demon", new_demon_path, class: "nav-link #{"active" if current_page?(new_demon_path)}" %></li>
          <% if (current_user && policy(User).index? ) %>
           <li class="nav-item"><%= link_to "Users", users_path, class: "nav-link #{"active" if current_page?(users_path)}" %></li>
          <% end %>
          <li class="nav-item"><%= link_to "About", about_path, class: "nav-link #{"active" if current_page?(about_path)}" %></li>
           <li class="nav-item">
            <% if user_signed_in? %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
            <% else %>
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KarnovAfterlife</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>

    <div class="d-flex flex-column min-vh-100">
        <%= render "shared/navbar" %>

        <div class="container p-4 p-md-5">
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
        <% end %>
        
          <%= yield %>
          
        </div>

        <%= render "layouts/footer" %>
    </div>

  </body>
</html>

app/views/pages/about.html.erb
<div class="position-absolute top-50 start-50 translate-middle text-center">
  <h2>We are an amazing team of the most advanced mentors and not lest advanced trainees!</h2>
</div>

app/views/pages/home.html.erb
<div
  class="bg-image"
  style= "background-image: url('https://i.redd.it/neia1gsl0m161.jpg'); height: 100vh;"
  >
    <div class="mask" style="background-color: rgba(0, 0, 0, 0.6);">
    <div class="d-flex justify-content-center align-items-center h-100">
      <h1 class="text-white mb-0">Eternal DamnationBnb</h1>
    </div>
  </div>
</div>

app/views/reviews/_new_review.html.erb
<%= form_with model: [demon, review], class: " card p-3 d-flex flex-column align-items-start" do |f| %>
  <%= f.label :comment, class: "form-label" %>
  <%= f.text_field :comment, class: "form-control" %>
  <%= f.label :rating, class: "form-label" %>
  <%= f.number_field :rating, class: "mb-3 form-control" %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/reviews/_review.html.erb
<li class="list-group-item p-3">
  <div class="row">
    <div class="col-8">
      <h5 class="mb-3"><%= review.user.name %></h5>
      <p class="m-0"><%= review.comment %></p>
    </div>
    <div class="col-4 text-end">
      <span class="badge bg-primary rounded-pill mb-2"><%= review.rating %></span>
      <% if review.user == user %>
        <%= button_to "Delete", review_path(review), method: :delete, class: "btn btn-danger" %>
      <% end %>  
    </div>
  </div>
</li>

app/views/shared/_navbar.html.erb
<header class="bg-primary">
  <nav class="navbar navbar-expand-lg">
    <div class="container">
      <div class="p-2">
        <h1><%= link_to "IIIKarnov Academy", root_path, class: "navbar-brand m-0 fs-4" %></h1>
      </div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ms-auto">
          <%= yield(:navbar_search) %>
          <li class="nav-item"><%= link_to "Home", home_path, class: "nav-link #{"active" if current_page?(home_path) || current_page?(root_path)}" %></li>
          <li class="nav-item"><%= link_to "My bookings", bookings_path, class: "nav-link #{"active" if current_page?(bookings_path)}" %></li>
          <li class="nav-item"><%= link_to "New booking", new_booking_path, class: "nav-link #{"active" if current_page?(new_booking_path)}" %></li>
          <li class="nav-item"><%= link_to "Demons", demons_path, class: "nav-link #{"active" if current_page?(demons_path)}" %></li>
          <li class="nav-item"><%= link_to "New demon", new_demon_path, class: "nav-link #{"active" if current_page?(new_demon_path)}" %></li>
          <% if (current_user && policy(User).index? ) %>
           <li class="nav-item"><%= link_to "Users", users_path, class: "nav-link #{"active" if current_page?(users_path)}" %></li>
          <% end %>
          <li class="nav-item"><%= link_to "About", about_path, class: "nav-link #{"active" if current_page?(about_path)}" %></li>
           <li class="nav-item">
            <% if user_signed_in? %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
            <% else %>
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_navbar_search.html.erb
<li class="nav-item me-3">  
  <%= form_with url: search_path, method: :get, class: "d-flex align-items-center gap-2"  do |f| %>
    <%= f.text_field :name %>
    <%= f.submit "Search", class: "btn" %>
  <% end %>
</li>

app/views/users/edit.html.erb
<h2>User <%= @user.name %></h2>
<%= form_with model: @user do |f| %>
  <%= f.collection_check_boxes :role_ids, Role.all, :id, :name %>
  <%= f.submit class: "btn btn-secondary" %>
<% end %>

app/views/users/index.html.erb
<h2>All users</h2>
<ul class="list-group">
  <% @users.each do |user| %>
    <li class="list-group-item">
      <h4><%= user.name %></h4>
      <p>Email: <%= user.email %></p>
      <p>Roles: <%= user.roles.pluck(:name) %></p>
      <%= link_to "Edit role", edit_user_path(user), class: "btn btn-secondary" %>
    </li>
  <% end %>
</ul>